Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	filter_GENE_with_families
	2

rule filter_GENE_with_families:
    input: 18Anopheles_dataset/data/INPUT_DATA/unrooted_raw_trees.nwk, 18Anopheles_dataset/data/INPUT_DATA/GFF, 18Anopheles_dataset/data/GFF_to_GENE_files/sorted_GENE
    output: 18Anopheles_dataset/data/GFF_to_GENE_files/filtered_GENE
    log: 18Anopheles_dataset/logs/GFF_to_GENE_files/filter_GENE_with_families.log
    jobid: 1

Error in rule filter_GENE_with_families:
    jobid: 1
    output: 18Anopheles_dataset/data/GFF_to_GENE_files/filtered_GENE
    log: 18Anopheles_dataset/logs/GFF_to_GENE_files/filter_GENE_with_families.log

RuleException:
CalledProcessError in line 57 of /home/yanselmetti/Bureau/DeCoSTAR_pipeline/preprocessing.snakefile:
Command ' set -euo pipefail;  bin/scripts/pipeline_input_decostar/filter_GENE_with_families.sh 18Anopheles_dataset/data/INPUT_DATA/unrooted_raw_trees.nwk 18Anopheles_dataset/data/INPUT_DATA/GFF 18Anopheles_dataset/data/GFF_to_GENE_files/sorted_GENE 18Anopheles_dataset/data/GFF_to_GENE_files/filtered_GENE ' returned non-zero exit status 1.
  File "/home/yanselmetti/Bureau/DeCoSTAR_pipeline/preprocessing.snakefile", line 57, in __rule_filter_GENE_with_families
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2017-10-18T090530.719200.snakemake.log
